/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.PenaltyTicket.PenaltyTicket_Frame;
import GUI.PurchaseTicket.PurchaseTicket_Frame;
import GUI.ReturnTicket.ReturnTicket_Frame;
import GUI.BorrowTicket.BorrowTicket_Frame;
import GUI.Member.Member_Frame;
import GUI.Book.Book_Frame;
import GUI.Staff.Staff_Frame;
import DTO.AccountDTO;
import DTO.SessionManager;
import GUI.Permission.PermissionDialog;
import GUI.Permission.Permission_Frame;

/**
 *
 * @author hieun
 */
public class Home_Frame extends javax.swing.JFrame {    
    /**
     * Creates new form Home_Panel
     */
    public Home_Frame() {
        initComponents();
        
        AccountDTO account = SessionManager.getInstance().getLoggedInAccount();
        setWelcomeText(account.getUsername());    
    }
    
    public void setWelcomeText(String username) {
        String label_Text = "Xin chào, " + username;
        welcome_Label.setText(label_Text);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        welcome_Label = new javax.swing.JLabel();
        navbar_Panel = new javax.swing.JPanel();
        openStaffFrame_Button = new javax.swing.JButton();
        openBookFrame_Button = new javax.swing.JButton();
        openMember_Button = new javax.swing.JButton();
        openBorrowTicketFrame_Button = new javax.swing.JButton();
        openReturnTicketFrame_Button = new javax.swing.JButton();
        openPurchaseTicketFrameButton = new javax.swing.JButton();
        openPenaltyTicketFrame_Button = new javax.swing.JButton();
        openPermissionFrame_Button = new javax.swing.JButton();
        openPermissionFrame_Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header_Panel.setBackground(new java.awt.Color(3, 169, 244));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Management System");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        welcome_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome_Label.setForeground(new java.awt.Color(255, 255, 255));
        welcome_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_Label.setText("Xin chào");

        javax.swing.GroupLayout header_PanelLayout = new javax.swing.GroupLayout(header_Panel);
        header_Panel.setLayout(header_PanelLayout);
        header_PanelLayout.setHorizontalGroup(
            header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcome_Label)
                .addGap(15, 15, 15))
        );
        header_PanelLayout.setVerticalGroup(
            header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(welcome_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        openStaffFrame_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openStaffFrame_Button.setText("Nhân viên");
        openStaffFrame_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openStaffFrame_ButtonActionPerformed(evt);
            }
        });

        openBookFrame_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openBookFrame_Button.setText("Quản lý sách");
        openBookFrame_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBookFrame_ButtonActionPerformed(evt);
            }
        });

        openMember_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openMember_Button.setText("Thành viên");
        openMember_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMember_ButtonActionPerformed(evt);
            }
        });

        openBorrowTicketFrame_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openBorrowTicketFrame_Button.setText("Mượn sách");
        openBorrowTicketFrame_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBorrowTicketFrame_ButtonActionPerformed(evt);
            }
        });

        openReturnTicketFrame_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openReturnTicketFrame_Button.setText("Trả sách");
        openReturnTicketFrame_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openReturnTicketFrame_ButtonActionPerformed(evt);
            }
        });

        openPurchaseTicketFrameButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openPurchaseTicketFrameButton.setText("Nhập sách ");
        openPurchaseTicketFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPurchaseTicketFrameButtonActionPerformed(evt);
            }
        });

        openPenaltyTicketFrame_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openPenaltyTicketFrame_Button.setText("Vi phạm");
        openPenaltyTicketFrame_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPenaltyTicketFrame_ButtonActionPerformed(evt);
            }
        });

        openPermissionFrame_Button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openPermissionFrame_Button.setText("Phân quyền");
        openPermissionFrame_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPermissionFrame_ButtonActionPerformed(evt);
            }
        });

        openPermissionFrame_Button1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openPermissionFrame_Button1.setText("Thống kê");
        openPermissionFrame_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPermissionFrame_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbar_PanelLayout = new javax.swing.GroupLayout(navbar_Panel);
        navbar_Panel.setLayout(navbar_PanelLayout);
        navbar_PanelLayout.setHorizontalGroup(
            navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_PanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openBorrowTicketFrame_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openStaffFrame_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openPenaltyTicketFrame_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openReturnTicketFrame_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openPermissionFrame_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openBookFrame_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openMember_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openPurchaseTicketFrameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openPermissionFrame_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        navbar_PanelLayout.setVerticalGroup(
            navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_PanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openStaffFrame_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openBookFrame_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openMember_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openBorrowTicketFrame_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openReturnTicketFrame_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openPurchaseTicketFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openPenaltyTicketFrame_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openPermissionFrame_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openPermissionFrame_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navbar_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navbar_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openStaffFrame_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openStaffFrame_ButtonActionPerformed
        new Staff_Frame().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_openStaffFrame_ButtonActionPerformed

    private void openBookFrame_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBookFrame_ButtonActionPerformed
        new Book_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openBookFrame_ButtonActionPerformed

    private void openMember_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMember_ButtonActionPerformed
        new Member_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openMember_ButtonActionPerformed

    private void openBorrowTicketFrame_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBorrowTicketFrame_ButtonActionPerformed
        new BorrowTicket_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openBorrowTicketFrame_ButtonActionPerformed

    private void openReturnTicketFrame_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openReturnTicketFrame_ButtonActionPerformed
        new ReturnTicket_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openReturnTicketFrame_ButtonActionPerformed

    private void openPurchaseTicketFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPurchaseTicketFrameButtonActionPerformed
        new PurchaseTicket_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openPurchaseTicketFrameButtonActionPerformed

    private void openPenaltyTicketFrame_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPenaltyTicketFrame_ButtonActionPerformed
        new PenaltyTicket_Frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openPenaltyTicketFrame_ButtonActionPerformed

    private void openPermissionFrame_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPermissionFrame_ButtonActionPerformed
//        new Permission_Frame().setVisible(true);
//        PermissionDialog permissionDialog = new PermissionDialog(null, true);
//        permissionDialog.setVisible(true);
        new PermissionDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openPermissionFrame_ButtonActionPerformed

    private void openPermissionFrame_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPermissionFrame_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openPermissionFrame_Button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel navbar_Panel;
    private javax.swing.JButton openBookFrame_Button;
    private javax.swing.JButton openBorrowTicketFrame_Button;
    private javax.swing.JButton openMember_Button;
    private javax.swing.JButton openPenaltyTicketFrame_Button;
    private javax.swing.JButton openPermissionFrame_Button;
    private javax.swing.JButton openPermissionFrame_Button1;
    private javax.swing.JButton openPurchaseTicketFrameButton;
    private javax.swing.JButton openReturnTicketFrame_Button;
    private javax.swing.JButton openStaffFrame_Button;
    private javax.swing.JLabel welcome_Label;
    // End of variables declaration//GEN-END:variables
}
