/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Book;

import GUI.ActionOnGUI;
import GUI.Home_Frame;

/**
 *
 * @author hieun
 */
public class Book_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Book_Frame
     */
    public Book_Frame() {
        initComponents();
        
        ActionOnGUI.disposeAndOpenNewFrame(Book_Frame.this, new Home_Frame()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        Book_Panel = new javax.swing.JPanel();
        addBook_Button = new javax.swing.JButton();
        editBook_Button = new javax.swing.JButton();
        viewBookItem = new javax.swing.JButton();
        Separator1 = new javax.swing.JSeparator();
        searchBook_TextField = new javax.swing.JTextField();
        refreshBookTable_Button = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        book_Table = new javax.swing.JTable();
        Bookshelf_Panel = new javax.swing.JPanel();
        addBookshelf_Button = new javax.swing.JButton();
        editBookshelf_Button = new javax.swing.JButton();
        deleteBookshelf_Button = new javax.swing.JButton();
        Separator3 = new javax.swing.JSeparator();
        searchBookshelf_TextField = new javax.swing.JTextField();
        refreshBookshelfTable_Button = new javax.swing.JButton();
        ScrollPane2 = new javax.swing.JScrollPane();
        bookshelfTable_Table = new javax.swing.JTable();
        placeBookOnShelf_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookItemTable_Table = new javax.swing.JTable();
        Category_Panel = new javax.swing.JPanel();
        addCategory_Button = new javax.swing.JButton();
        editCategory_Button = new javax.swing.JButton();
        deleteCategory_Button = new javax.swing.JButton();
        Separator2 = new javax.swing.JSeparator();
        searchCategory_TextField = new javax.swing.JTextField();
        refreshCategoryTable_Button = new javax.swing.JButton();
        ScrollPane1 = new javax.swing.JScrollPane();
        categoryTable_Table = new javax.swing.JTable();
        Publisher_Panel = new javax.swing.JPanel();
        addPublisher_Button = new javax.swing.JButton();
        editPublisher_Button = new javax.swing.JButton();
        deletePublisher_Button = new javax.swing.JButton();
        Separator4 = new javax.swing.JSeparator();
        searchPublisher_TextField = new javax.swing.JTextField();
        refreshPublisherTable_Button = new javax.swing.JButton();
        ScrollPane3 = new javax.swing.JScrollPane();
        publisherTable_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addBook_Button.setBackground(new java.awt.Color(82, 196, 26));
        addBook_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addBook_Button.setForeground(new java.awt.Color(255, 255, 255));
        addBook_Button.setText("Thêm");
        addBook_Button.setBorderPainted(false);
        addBook_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBook_Button.setFocusPainted(false);
        addBook_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBook_ButtonActionPerformed(evt);
            }
        });

        editBook_Button.setBackground(new java.awt.Color(250, 173, 20));
        editBook_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editBook_Button.setForeground(new java.awt.Color(255, 255, 255));
        editBook_Button.setText("Sửa");
        editBook_Button.setBorderPainted(false);
        editBook_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBook_Button.setFocusPainted(false);
        editBook_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBook_ButtonActionPerformed(evt);
            }
        });

        viewBookItem.setBackground(new java.awt.Color(24, 144, 255));
        viewBookItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewBookItem.setForeground(new java.awt.Color(255, 255, 255));
        viewBookItem.setText("Xem");
        viewBookItem.setBorderPainted(false);
        viewBookItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBookItem.setFocusPainted(false);
        viewBookItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookItemActionPerformed(evt);
            }
        });

        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchBook_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        refreshBookTable_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshBookTable_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshBookTable_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshBookTable_Button.setText("Làm mới");
        refreshBookTable_Button.setBorderPainted(false);
        refreshBookTable_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshBookTable_Button.setFocusPainted(false);
        refreshBookTable_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBookTable_ButtonActionPerformed(evt);
            }
        });

        book_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        book_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Tên sách", "Tác giả", "Mã nhà xuất bản", "Năm xuất bản", "Mã thể loại", "Số lượng"
            }
        ));
        ScrollPane.setViewportView(book_Table);

        javax.swing.GroupLayout Book_PanelLayout = new javax.swing.GroupLayout(Book_Panel);
        Book_Panel.setLayout(Book_PanelLayout);
        Book_PanelLayout.setHorizontalGroup(
            Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Book_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Book_PanelLayout.createSequentialGroup()
                        .addComponent(addBook_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editBook_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewBookItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBook_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBookTable_Button)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(Book_PanelLayout.createSequentialGroup()
                        .addComponent(ScrollPane)
                        .addGap(12, 12, 12))))
        );
        Book_PanelLayout.setVerticalGroup(
            Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Book_PanelLayout.createSequentialGroup()
                .addGroup(Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Book_PanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBook_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBook_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewBookItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBook_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshBookTable_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        TabbedPane.addTab("Sách", Book_Panel);

        addBookshelf_Button.setBackground(new java.awt.Color(82, 196, 26));
        addBookshelf_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addBookshelf_Button.setForeground(new java.awt.Color(255, 255, 255));
        addBookshelf_Button.setText("Thêm");
        addBookshelf_Button.setBorderPainted(false);
        addBookshelf_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBookshelf_Button.setFocusPainted(false);
        addBookshelf_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookshelf_ButtonActionPerformed(evt);
            }
        });

        editBookshelf_Button.setBackground(new java.awt.Color(250, 173, 20));
        editBookshelf_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editBookshelf_Button.setForeground(new java.awt.Color(255, 255, 255));
        editBookshelf_Button.setText("Sửa");
        editBookshelf_Button.setBorderPainted(false);
        editBookshelf_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBookshelf_Button.setFocusPainted(false);
        editBookshelf_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookshelf_ButtonActionPerformed(evt);
            }
        });

        deleteBookshelf_Button.setBackground(new java.awt.Color(255, 77, 79));
        deleteBookshelf_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteBookshelf_Button.setForeground(new java.awt.Color(255, 255, 255));
        deleteBookshelf_Button.setText("Xóa");
        deleteBookshelf_Button.setBorderPainted(false);
        deleteBookshelf_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBookshelf_Button.setFocusPainted(false);
        deleteBookshelf_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookshelf_ButtonActionPerformed(evt);
            }
        });

        Separator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchBookshelf_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        refreshBookshelfTable_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshBookshelfTable_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshBookshelfTable_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshBookshelfTable_Button.setText("Làm mới");
        refreshBookshelfTable_Button.setBorderPainted(false);
        refreshBookshelfTable_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshBookshelfTable_Button.setFocusPainted(false);
        refreshBookshelfTable_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBookshelfTable_ButtonActionPerformed(evt);
            }
        });

        bookshelfTable_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookshelfTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã kệ sách", "Tên kệ sách", "Sức chứa (sách)"
            }
        ));
        ScrollPane2.setViewportView(bookshelfTable_Table);

        placeBookOnShelf_Button.setBackground(new java.awt.Color(24, 144, 255));
        placeBookOnShelf_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        placeBookOnShelf_Button.setForeground(new java.awt.Color(255, 255, 255));
        placeBookOnShelf_Button.setText("Xếp sách");
        placeBookOnShelf_Button.setBorderPainted(false);
        placeBookOnShelf_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        placeBookOnShelf_Button.setFocusPainted(false);
        placeBookOnShelf_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBookOnShelf_ButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Kệ sách");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Sách trên kệ");

        bookItemTable_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookItemTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bản sách", "Mã sách", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(bookItemTable_Table);

        javax.swing.GroupLayout Bookshelf_PanelLayout = new javax.swing.GroupLayout(Bookshelf_Panel);
        Bookshelf_Panel.setLayout(Bookshelf_PanelLayout);
        Bookshelf_PanelLayout.setHorizontalGroup(
            Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bookshelf_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Bookshelf_PanelLayout.createSequentialGroup()
                        .addComponent(addBookshelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editBookshelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBookshelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(placeBookOnShelf_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBookshelf_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBookshelfTable_Button))
                    .addGroup(Bookshelf_PanelLayout.createSequentialGroup()
                        .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        Bookshelf_PanelLayout.setVerticalGroup(
            Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bookshelf_PanelLayout.createSequentialGroup()
                .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Bookshelf_PanelLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addBookshelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editBookshelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteBookshelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(placeBookOnShelf_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBookshelf_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshBookshelfTable_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Separator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Bookshelf_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Kệ sách", Bookshelf_Panel);

        addCategory_Button.setBackground(new java.awt.Color(82, 196, 26));
        addCategory_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addCategory_Button.setForeground(new java.awt.Color(255, 255, 255));
        addCategory_Button.setText("Thêm");
        addCategory_Button.setBorderPainted(false);
        addCategory_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCategory_Button.setFocusPainted(false);
        addCategory_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategory_ButtonActionPerformed(evt);
            }
        });

        editCategory_Button.setBackground(new java.awt.Color(250, 173, 20));
        editCategory_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editCategory_Button.setForeground(new java.awt.Color(255, 255, 255));
        editCategory_Button.setText("Sửa");
        editCategory_Button.setBorderPainted(false);
        editCategory_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editCategory_Button.setFocusPainted(false);
        editCategory_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategory_ButtonActionPerformed(evt);
            }
        });

        deleteCategory_Button.setBackground(new java.awt.Color(255, 77, 79));
        deleteCategory_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteCategory_Button.setForeground(new java.awt.Color(255, 255, 255));
        deleteCategory_Button.setText("Xóa");
        deleteCategory_Button.setBorderPainted(false);
        deleteCategory_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCategory_Button.setFocusPainted(false);
        deleteCategory_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategory_ButtonActionPerformed(evt);
            }
        });

        Separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchCategory_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        refreshCategoryTable_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshCategoryTable_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshCategoryTable_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshCategoryTable_Button.setText("Làm mới");
        refreshCategoryTable_Button.setBorderPainted(false);
        refreshCategoryTable_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshCategoryTable_Button.setFocusPainted(false);
        refreshCategoryTable_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCategoryTable_ButtonActionPerformed(evt);
            }
        });

        categoryTable_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã thể loại", "Tên thể loại"
            }
        ));
        ScrollPane1.setViewportView(categoryTable_Table);

        javax.swing.GroupLayout Category_PanelLayout = new javax.swing.GroupLayout(Category_Panel);
        Category_Panel.setLayout(Category_PanelLayout);
        Category_PanelLayout.setHorizontalGroup(
            Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Category_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Category_PanelLayout.createSequentialGroup()
                        .addComponent(addCategory_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editCategory_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCategory_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCategory_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshCategoryTable_Button)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(Category_PanelLayout.createSequentialGroup()
                        .addComponent(ScrollPane1)
                        .addGap(12, 12, 12))))
        );
        Category_PanelLayout.setVerticalGroup(
            Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Category_PanelLayout.createSequentialGroup()
                .addGroup(Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Category_PanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCategory_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCategory_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteCategory_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchCategory_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshCategoryTable_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        TabbedPane.addTab("Thể loại", Category_Panel);

        addPublisher_Button.setBackground(new java.awt.Color(82, 196, 26));
        addPublisher_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPublisher_Button.setForeground(new java.awt.Color(255, 255, 255));
        addPublisher_Button.setText("Thêm");
        addPublisher_Button.setBorderPainted(false);
        addPublisher_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPublisher_Button.setFocusPainted(false);
        addPublisher_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPublisher_ButtonActionPerformed(evt);
            }
        });

        editPublisher_Button.setBackground(new java.awt.Color(250, 173, 20));
        editPublisher_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editPublisher_Button.setForeground(new java.awt.Color(255, 255, 255));
        editPublisher_Button.setText("Sửa");
        editPublisher_Button.setBorderPainted(false);
        editPublisher_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPublisher_Button.setFocusPainted(false);
        editPublisher_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPublisher_ButtonActionPerformed(evt);
            }
        });

        deletePublisher_Button.setBackground(new java.awt.Color(255, 77, 79));
        deletePublisher_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletePublisher_Button.setForeground(new java.awt.Color(255, 255, 255));
        deletePublisher_Button.setText("Xóa");
        deletePublisher_Button.setBorderPainted(false);
        deletePublisher_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletePublisher_Button.setFocusPainted(false);
        deletePublisher_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePublisher_ButtonActionPerformed(evt);
            }
        });

        Separator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchPublisher_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        refreshPublisherTable_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshPublisherTable_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshPublisherTable_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshPublisherTable_Button.setText("Làm mới");
        refreshPublisherTable_Button.setBorderPainted(false);
        refreshPublisherTable_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshPublisherTable_Button.setFocusPainted(false);
        refreshPublisherTable_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPublisherTable_ButtonActionPerformed(evt);
            }
        });

        publisherTable_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        publisherTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà xuất bản", "Tên nhà xuất bản", "Địa chỉ", "Số điện thoại"
            }
        ));
        ScrollPane3.setViewportView(publisherTable_Table);

        javax.swing.GroupLayout Publisher_PanelLayout = new javax.swing.GroupLayout(Publisher_Panel);
        Publisher_Panel.setLayout(Publisher_PanelLayout);
        Publisher_PanelLayout.setHorizontalGroup(
            Publisher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Publisher_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Publisher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Publisher_PanelLayout.createSequentialGroup()
                        .addComponent(addPublisher_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editPublisher_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletePublisher_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPublisher_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshPublisherTable_Button)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(Publisher_PanelLayout.createSequentialGroup()
                        .addComponent(ScrollPane3)
                        .addGap(12, 12, 12))))
        );
        Publisher_PanelLayout.setVerticalGroup(
            Publisher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Publisher_PanelLayout.createSequentialGroup()
                .addGroup(Publisher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Publisher_PanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Publisher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPublisher_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPublisher_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePublisher_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Separator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Publisher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchPublisher_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshPublisherTable_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        TabbedPane.addTab("Nhà xuất bản", Publisher_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBook_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBook_ButtonActionPerformed
        new AddBook_Frame().setVisible(true);
    }//GEN-LAST:event_addBook_ButtonActionPerformed

    private void editBook_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBook_ButtonActionPerformed
//        int index = staff_Table.getSelectedRow();
//        TableModel model = staff_Table.getModel();
//
//        if (index == -1) {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//
//        String id = model.getValueAt(index, 0).toString();
//        String fullName = model.getValueAt(index, 1).toString();
//        String email = model.getValueAt(index, 2).toString();
//        String phone = model.getValueAt(index, 3).toString();
//        String address = model.getValueAt(index, 4).toString();
//        String hireDate = model.getValueAt(index, 5).toString();
//        int status = ("Đang làm việc".equals(model.getValueAt(index, 6).toString())) ? 0 : 1;
//
        EditBook_Frame editBook_Frame = new EditBook_Frame();
        editBook_Frame.setVisible(true);
//
//        editStaff_Frame.id_TextField.setText(id);
//        editStaff_Frame.fullname_TextField.setText(fullName);
//        editStaff_Frame.email_TextField.setText(email);
//        editStaff_Frame.phone_TextField.setText(phone);
//        editStaff_Frame.address_TextField.setText(address);
//        editStaff_Frame.hireDate_TextField.setText(hireDate);
//        editStaff_Frame.status_ComboBox.setSelectedIndex(status);
    }//GEN-LAST:event_editBook_ButtonActionPerformed

    private void refreshBookTable_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBookTable_ButtonActionPerformed
//        DefaultTableModel tableModel = (DefaultTableModel) staff_Table.getModel();
//        ActionOnGUI.showDataOnTable(tableModel, staffBUS.getAllStaff());
//
//        search_TextField.setText("");
//        status_ComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_refreshBookTable_ButtonActionPerformed

    private void viewBookItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookItemActionPerformed
        new ViewBookItem_Frame().setVisible(true); 
    }//GEN-LAST:event_viewBookItemActionPerformed

    private void addCategory_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategory_ButtonActionPerformed
        new AddCategory_Frame().setVisible(true); 
    }//GEN-LAST:event_addCategory_ButtonActionPerformed

    private void editCategory_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategory_ButtonActionPerformed
        new EditCategory_Frame().setVisible(true); 
    }//GEN-LAST:event_editCategory_ButtonActionPerformed

    private void deleteCategory_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCategory_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCategory_ButtonActionPerformed

    private void refreshCategoryTable_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCategoryTable_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshCategoryTable_ButtonActionPerformed

    private void addBookshelf_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookshelf_ButtonActionPerformed
        new AddBookshelf_Frame().setVisible(true); 
    }//GEN-LAST:event_addBookshelf_ButtonActionPerformed

    private void editBookshelf_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookshelf_ButtonActionPerformed
        EditBookshelf_Frame editBookshelf_Frame = new EditBookshelf_Frame();
        editBookshelf_Frame.setVisible(true); 
    }//GEN-LAST:event_editBookshelf_ButtonActionPerformed

    private void refreshBookshelfTable_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBookshelfTable_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBookshelfTable_ButtonActionPerformed

    private void placeBookOnShelf_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBookOnShelf_ButtonActionPerformed
        new BookShelving_Frame().setVisible(true); 
    }//GEN-LAST:event_placeBookOnShelf_ButtonActionPerformed

    private void deleteBookshelf_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookshelf_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBookshelf_ButtonActionPerformed

    private void addPublisher_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPublisher_ButtonActionPerformed
        new AddPublisher_Frame().setVisible(true); 
    }//GEN-LAST:event_addPublisher_ButtonActionPerformed

    private void editPublisher_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPublisher_ButtonActionPerformed
        new EditPublisher_Frame().setVisible(true); 
    }//GEN-LAST:event_editPublisher_ButtonActionPerformed

    private void deletePublisher_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePublisher_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePublisher_ButtonActionPerformed

    private void refreshPublisherTable_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPublisherTable_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshPublisherTable_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Book_Panel;
    private javax.swing.JPanel Bookshelf_Panel;
    private javax.swing.JPanel Category_Panel;
    private javax.swing.JPanel Publisher_Panel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    private javax.swing.JScrollPane ScrollPane3;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton addBook_Button;
    private javax.swing.JButton addBookshelf_Button;
    private javax.swing.JButton addCategory_Button;
    private javax.swing.JButton addPublisher_Button;
    private javax.swing.JTable bookItemTable_Table;
    private javax.swing.JTable book_Table;
    private javax.swing.JTable bookshelfTable_Table;
    private javax.swing.JTable categoryTable_Table;
    private javax.swing.JButton deleteBookshelf_Button;
    private javax.swing.JButton deleteCategory_Button;
    private javax.swing.JButton deletePublisher_Button;
    private javax.swing.JButton editBook_Button;
    private javax.swing.JButton editBookshelf_Button;
    private javax.swing.JButton editCategory_Button;
    private javax.swing.JButton editPublisher_Button;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeBookOnShelf_Button;
    private javax.swing.JTable publisherTable_Table;
    private javax.swing.JButton refreshBookTable_Button;
    private javax.swing.JButton refreshBookshelfTable_Button;
    private javax.swing.JButton refreshCategoryTable_Button;
    private javax.swing.JButton refreshPublisherTable_Button;
    private javax.swing.JTextField searchBook_TextField;
    private javax.swing.JTextField searchBookshelf_TextField;
    private javax.swing.JTextField searchCategory_TextField;
    private javax.swing.JTextField searchPublisher_TextField;
    private javax.swing.JButton viewBookItem;
    // End of variables declaration//GEN-END:variables
}
