/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.PurchaseTicket;

import GUI.ActionOnGUI;
import GUI.Home_Frame;
import GUI.PurchaseTicket.AddPurchaseTicket_Frame;

/**
 *
 * @author hieun
 */
public class PurchaseTicket_Frame extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseTicket_Frame1
     */
    public PurchaseTicket_Frame() {
        initComponents();
        
        ActionOnGUI.disposeAndOpenNewFrame(PurchaseTicket_Frame.this, new Home_Frame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        purchaseTicket_Panel = new javax.swing.JPanel();
        addPurchaseTicket_Button = new javax.swing.JButton();
        cancelPuchaseTicket_Button = new javax.swing.JButton();
        Separator1 = new javax.swing.JSeparator();
        searchPurchaseTicket_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fromDate_DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        toDate_DateChooser = new com.toedter.calendar.JDateChooser();
        refreshPurchaseTicket_Button = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        purchaseTicket_Table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseDetails_Table = new javax.swing.JTable();
        supplier_Panel = new javax.swing.JPanel();
        addSupplier_Button = new javax.swing.JButton();
        editSupplier_Button = new javax.swing.JButton();
        editSupplier_Button1 = new javax.swing.JButton();
        searchSupplier_TextField = new javax.swing.JTextField();
        Separator2 = new javax.swing.JSeparator();
        refreshSupplier_Button = new javax.swing.JButton();
        ScrollPane1 = new javax.swing.JScrollPane();
        supplier_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addPurchaseTicket_Button.setBackground(new java.awt.Color(82, 196, 26));
        addPurchaseTicket_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPurchaseTicket_Button.setForeground(new java.awt.Color(255, 255, 255));
        addPurchaseTicket_Button.setText("Thêm");
        addPurchaseTicket_Button.setBorderPainted(false);
        addPurchaseTicket_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPurchaseTicket_Button.setFocusPainted(false);
        addPurchaseTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPurchaseTicket_ButtonActionPerformed(evt);
            }
        });

        cancelPuchaseTicket_Button.setBackground(new java.awt.Color(255, 77, 79));
        cancelPuchaseTicket_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelPuchaseTicket_Button.setForeground(new java.awt.Color(255, 255, 255));
        cancelPuchaseTicket_Button.setText("Hủy");
        cancelPuchaseTicket_Button.setBorderPainted(false);
        cancelPuchaseTicket_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelPuchaseTicket_Button.setFocusPainted(false);
        cancelPuchaseTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPuchaseTicket_ButtonActionPerformed(evt);
            }
        });

        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchPurchaseTicket_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Từ ngày");

        fromDate_DateChooser.setDateFormatString("yyyy-MM-dd");
        fromDate_DateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Đến ngày");

        toDate_DateChooser.setDateFormatString("yyyy-MM-dd");
        toDate_DateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        refreshPurchaseTicket_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshPurchaseTicket_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshPurchaseTicket_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshPurchaseTicket_Button.setText("Làm mới");
        refreshPurchaseTicket_Button.setBorderPainted(false);
        refreshPurchaseTicket_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshPurchaseTicket_Button.setFocusPainted(false);
        refreshPurchaseTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPurchaseTicket_ButtonActionPerformed(evt);
            }
        });

        purchaseTicket_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        purchaseTicket_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã nhà cung cấp", "Mã nhân viên", "Ngày nhập", "Trạng thái"
            }
        ));
        ScrollPane.setViewportView(purchaseTicket_Table);

        purchaseDetails_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        purchaseDetails_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã CT phiếu nhập", "Mã phiếu nhập", "ISBN", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(purchaseDetails_Table);

        javax.swing.GroupLayout purchaseTicket_PanelLayout = new javax.swing.GroupLayout(purchaseTicket_Panel);
        purchaseTicket_Panel.setLayout(purchaseTicket_PanelLayout);
        purchaseTicket_PanelLayout.setHorizontalGroup(
            purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseTicket_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchaseTicket_PanelLayout.createSequentialGroup()
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purchaseTicket_PanelLayout.createSequentialGroup()
                        .addComponent(addPurchaseTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelPuchaseTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPurchaseTicket_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fromDate_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toDate_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshPurchaseTicket_Button)))
                .addGap(12, 12, 12))
        );
        purchaseTicket_PanelLayout.setVerticalGroup(
            purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseTicket_PanelLayout.createSequentialGroup()
                .addGroup(purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, purchaseTicket_PanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPurchaseTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelPuchaseTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fromDate_DateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchPurchaseTicket_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toDate_DateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(refreshPurchaseTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(purchaseTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Phiếu nhập", purchaseTicket_Panel);

        addSupplier_Button.setBackground(new java.awt.Color(82, 196, 26));
        addSupplier_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addSupplier_Button.setForeground(new java.awt.Color(255, 255, 255));
        addSupplier_Button.setText("Thêm");
        addSupplier_Button.setBorderPainted(false);
        addSupplier_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSupplier_Button.setFocusPainted(false);
        addSupplier_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplier_ButtonActionPerformed(evt);
            }
        });

        editSupplier_Button.setBackground(new java.awt.Color(250, 173, 20));
        editSupplier_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editSupplier_Button.setForeground(new java.awt.Color(255, 255, 255));
        editSupplier_Button.setText("Sửa");
        editSupplier_Button.setBorderPainted(false);
        editSupplier_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSupplier_Button.setFocusPainted(false);
        editSupplier_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSupplier_ButtonActionPerformed(evt);
            }
        });

        editSupplier_Button1.setBackground(new java.awt.Color(255, 77, 79));
        editSupplier_Button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editSupplier_Button1.setForeground(new java.awt.Color(255, 255, 255));
        editSupplier_Button1.setText("Xóa");
        editSupplier_Button1.setBorderPainted(false);
        editSupplier_Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSupplier_Button1.setFocusPainted(false);
        editSupplier_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSupplier_Button1ActionPerformed(evt);
            }
        });

        searchSupplier_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        refreshSupplier_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshSupplier_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshSupplier_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshSupplier_Button.setText("Làm mới");
        refreshSupplier_Button.setBorderPainted(false);
        refreshSupplier_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshSupplier_Button.setFocusPainted(false);
        refreshSupplier_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshSupplier_ButtonActionPerformed(evt);
            }
        });

        supplier_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplier_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại"
            }
        ));
        ScrollPane1.setViewportView(supplier_Table);

        javax.swing.GroupLayout supplier_PanelLayout = new javax.swing.GroupLayout(supplier_Panel);
        supplier_Panel.setLayout(supplier_PanelLayout);
        supplier_PanelLayout.setHorizontalGroup(
            supplier_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplier_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(supplier_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
                    .addGroup(supplier_PanelLayout.createSequentialGroup()
                        .addComponent(addSupplier_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editSupplier_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editSupplier_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchSupplier_TextField)
                        .addGap(18, 18, 18)
                        .addComponent(refreshSupplier_Button)))
                .addGap(12, 12, 12))
        );
        supplier_PanelLayout.setVerticalGroup(
            supplier_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplier_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(supplier_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshSupplier_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(supplier_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addSupplier_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editSupplier_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editSupplier_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Separator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchSupplier_TextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Nhà cung cấp", supplier_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPurchaseTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPurchaseTicket_ButtonActionPerformed
        new AddPurchaseTicket_Frame().setVisible(true); 
    }//GEN-LAST:event_addPurchaseTicket_ButtonActionPerformed

    private void cancelPuchaseTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPuchaseTicket_ButtonActionPerformed

    }//GEN-LAST:event_cancelPuchaseTicket_ButtonActionPerformed

    private void refreshPurchaseTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPurchaseTicket_ButtonActionPerformed

    }//GEN-LAST:event_refreshPurchaseTicket_ButtonActionPerformed

    private void addSupplier_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplier_ButtonActionPerformed
        new AddSupplier_Frame().setVisible(true);
    }//GEN-LAST:event_addSupplier_ButtonActionPerformed

    private void editSupplier_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSupplier_ButtonActionPerformed
        //        int index = staff_Table.getSelectedRow();
        //        TableModel model = staff_Table.getModel();
        //
        //        if (index == -1) {
            //            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            //            return;
            //        }
        //
        //        String id = model.getValueAt(index, 0).toString();
        //        String fullName = model.getValueAt(index, 1).toString();
        //        String email = model.getValueAt(index, 2).toString();
        //        String phone = model.getValueAt(index, 3).toString();
        //        String address = model.getValueAt(index, 4).toString();
        //        String hireDate = model.getValueAt(index, 5).toString();
        //        int status = ("Đang làm việc".equals(model.getValueAt(index, 6).toString())) ? 0 : 1;
        //
        EditSupplier_Frame editSupplier_Frame = new EditSupplier_Frame();
        editSupplier_Frame.setVisible(true); 
        //
        //        editStaff_Frame.id_TextField.setText(id);
        //        editStaff_Frame.fullname_TextField.setText(fullName);
        //        editStaff_Frame.email_TextField.setText(email);
        //        editStaff_Frame.phone_TextField.setText(phone);
        //        editStaff_Frame.address_TextField.setText(address);
        //        editStaff_Frame.hireDate_TextField.setText(hireDate);
        //        editStaff_Frame.status_ComboBox.setSelectedIndex(status);
    }//GEN-LAST:event_editSupplier_ButtonActionPerformed

    private void refreshSupplier_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshSupplier_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshSupplier_ButtonActionPerformed

    private void editSupplier_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSupplier_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSupplier_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseTicket_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JButton addPurchaseTicket_Button;
    private javax.swing.JButton addSupplier_Button;
    private javax.swing.JButton cancelPuchaseTicket_Button;
    private javax.swing.JButton deletePublisher_Button;
    private javax.swing.JButton deletePublisher_Button1;
    private javax.swing.JButton editSupplier_Button;
    private javax.swing.JButton editSupplier_Button1;
    private com.toedter.calendar.JDateChooser fromDate_DateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable purchaseDetails_Table;
    private javax.swing.JPanel purchaseTicket_Panel;
    private javax.swing.JTable purchaseTicket_Table;
    private javax.swing.JButton refreshPurchaseTicket_Button;
    private javax.swing.JButton refreshSupplier_Button;
    private javax.swing.JTextField searchPurchaseTicket_TextField;
    private javax.swing.JTextField searchSupplier_TextField;
    private javax.swing.JPanel supplier_Panel;
    private javax.swing.JTable supplier_Table;
    private com.toedter.calendar.JDateChooser toDate_DateChooser;
    // End of variables declaration//GEN-END:variables
}
