/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.PenaltyTicket;

import GUI.ActionOnGUI;
import GUI.Home_Frame;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author hieun
 */
public class PenaltyTicket_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Supplier_Frame
     */
    public PenaltyTicket_Frame() {
        initComponents();
        
        searchPenaltyTicket_TextField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Từ ngày"); 
        fromDate_DateChooser.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Từ ngày"); 
        
        ActionOnGUI.disposeAndOpenNewFrame(PenaltyTicket_Frame.this, new Home_Frame()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PenaltyTicket_Panel = new javax.swing.JPanel();
        addPenaltyTicket_Button = new javax.swing.JButton();
        editPenaltyTicket_Button = new javax.swing.JButton();
        Separator1 = new javax.swing.JSeparator();
        searchPenaltyTicket_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fromDate_DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        toDate_DateChooser = new com.toedter.calendar.JDateChooser();
        refreshPenaltyTicket_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        penaltyTicket_Table = new javax.swing.JTable();
        Penalty_Panel = new javax.swing.JPanel();
        addPenalty_Button = new javax.swing.JButton();
        editPenalty_Button = new javax.swing.JButton();
        Separator2 = new javax.swing.JSeparator();
        searchPenalty_TextField = new javax.swing.JTextField();
        refreshPenaltyTable_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        penalty_Table = new javax.swing.JTable();
        sort_ComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addPenaltyTicket_Button.setBackground(new java.awt.Color(82, 196, 26));
        addPenaltyTicket_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPenaltyTicket_Button.setForeground(new java.awt.Color(255, 255, 255));
        addPenaltyTicket_Button.setText("Thêm");
        addPenaltyTicket_Button.setBorderPainted(false);
        addPenaltyTicket_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPenaltyTicket_Button.setFocusPainted(false);
        addPenaltyTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPenaltyTicket_ButtonActionPerformed(evt);
            }
        });

        editPenaltyTicket_Button.setBackground(new java.awt.Color(250, 173, 20));
        editPenaltyTicket_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editPenaltyTicket_Button.setForeground(new java.awt.Color(255, 255, 255));
        editPenaltyTicket_Button.setText("Sửa");
        editPenaltyTicket_Button.setBorderPainted(false);
        editPenaltyTicket_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPenaltyTicket_Button.setFocusPainted(false);
        editPenaltyTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPenaltyTicket_ButtonActionPerformed(evt);
            }
        });

        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchPenaltyTicket_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Từ ngày");

        fromDate_DateChooser.setDateFormatString("yyyy-MM-dd");
        fromDate_DateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Đến ngày");

        toDate_DateChooser.setDateFormatString("yyyy-MM-dd");
        toDate_DateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        refreshPenaltyTicket_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshPenaltyTicket_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshPenaltyTicket_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshPenaltyTicket_Button.setText("Làm mới");
        refreshPenaltyTicket_Button.setBorderPainted(false);
        refreshPenaltyTicket_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshPenaltyTicket_Button.setFocusPainted(false);
        refreshPenaltyTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPenaltyTicket_ButtonActionPerformed(evt);
            }
        });

        penaltyTicket_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        penaltyTicket_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu phạt", "Mã thành viên", "Mã nhân viên", "Mã vi phạm", "Ngày tạo", "Ghi chú", "Tiền phạt"
            }
        ));
        jScrollPane1.setViewportView(penaltyTicket_Table);

        javax.swing.GroupLayout PenaltyTicket_PanelLayout = new javax.swing.GroupLayout(PenaltyTicket_Panel);
        PenaltyTicket_Panel.setLayout(PenaltyTicket_PanelLayout);
        PenaltyTicket_PanelLayout.setHorizontalGroup(
            PenaltyTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PenaltyTicket_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PenaltyTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PenaltyTicket_PanelLayout.createSequentialGroup()
                        .addComponent(addPenaltyTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editPenaltyTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPenaltyTicket_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fromDate_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toDate_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshPenaltyTicket_Button))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
        );
        PenaltyTicket_PanelLayout.setVerticalGroup(
            PenaltyTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PenaltyTicket_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PenaltyTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(refreshPenaltyTicket_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(fromDate_DateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PenaltyTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchPenaltyTicket_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Separator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PenaltyTicket_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPenaltyTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editPenaltyTicket_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toDate_DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Phiếu phạt", PenaltyTicket_Panel);

        addPenalty_Button.setBackground(new java.awt.Color(82, 196, 26));
        addPenalty_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPenalty_Button.setForeground(new java.awt.Color(255, 255, 255));
        addPenalty_Button.setText("Thêm");
        addPenalty_Button.setBorderPainted(false);
        addPenalty_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPenalty_Button.setFocusPainted(false);
        addPenalty_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPenalty_ButtonActionPerformed(evt);
            }
        });

        editPenalty_Button.setBackground(new java.awt.Color(250, 173, 20));
        editPenalty_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editPenalty_Button.setForeground(new java.awt.Color(255, 255, 255));
        editPenalty_Button.setText("Sửa");
        editPenalty_Button.setBorderPainted(false);
        editPenalty_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPenalty_Button.setFocusPainted(false);
        editPenalty_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPenalty_ButtonActionPerformed(evt);
            }
        });

        Separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        searchPenalty_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        refreshPenaltyTable_Button.setBackground(new java.awt.Color(24, 144, 255));
        refreshPenaltyTable_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refreshPenaltyTable_Button.setForeground(new java.awt.Color(255, 255, 255));
        refreshPenaltyTable_Button.setText("Làm mới");
        refreshPenaltyTable_Button.setBorderPainted(false);
        refreshPenaltyTable_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshPenaltyTable_Button.setFocusPainted(false);
        refreshPenaltyTable_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPenaltyTable_ButtonActionPerformed(evt);
            }
        });

        penalty_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        penalty_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã vi phạm", "Vi phạm", "Tiền phạt"
            }
        ));
        jScrollPane2.setViewportView(penalty_Table);

        sort_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sort_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tăng dần", "Giảm dần" }));
        sort_ComboBox.setSelectedIndex(-1);

        javax.swing.GroupLayout Penalty_PanelLayout = new javax.swing.GroupLayout(Penalty_Panel);
        Penalty_Panel.setLayout(Penalty_PanelLayout);
        Penalty_PanelLayout.setHorizontalGroup(
            Penalty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Penalty_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Penalty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
                    .addGroup(Penalty_PanelLayout.createSequentialGroup()
                        .addComponent(addPenalty_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editPenalty_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPenalty_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sort_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshPenaltyTable_Button)))
                .addGap(12, 12, 12))
        );
        Penalty_PanelLayout.setVerticalGroup(
            Penalty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Penalty_PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Penalty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Penalty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchPenalty_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshPenaltyTable_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Separator2)
                    .addGroup(Penalty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPenalty_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editPenalty_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sort_ComboBox))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Vi phạm", Penalty_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPenaltyTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPenaltyTicket_ButtonActionPerformed
        new AddPenaltyTicket_Frame().setVisible(true);
    }//GEN-LAST:event_addPenaltyTicket_ButtonActionPerformed

    private void editPenaltyTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPenaltyTicket_ButtonActionPerformed
        //        int index = staff_Table.getSelectedRow();
        //        TableModel model = staff_Table.getModel();
        //
        //        if (index == -1) {
            //            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            //            return;
            //        }
        //
        //        String id = model.getValueAt(index, 0).toString();
        //        String fullName = model.getValueAt(index, 1).toString();
        //        String email = model.getValueAt(index, 2).toString();
        //        String phone = model.getValueAt(index, 3).toString();
        //        String address = model.getValueAt(index, 4).toString();
        //        String hireDate = model.getValueAt(index, 5).toString();
        //        int status = ("Đang làm việc".equals(model.getValueAt(index, 6).toString())) ? 0 : 1;
        //
                EditPenaltyTicket_Frame editPenaltyTicket_Frame = new EditPenaltyTicket_Frame();
                editPenaltyTicket_Frame.setVisible(true); 
        //
        //        editStaff_Frame.id_TextField.setText(id);
        //        editStaff_Frame.fullname_TextField.setText(fullName);
        //        editStaff_Frame.email_TextField.setText(email);
        //        editStaff_Frame.phone_TextField.setText(phone);
        //        editStaff_Frame.address_TextField.setText(address);
        //        editStaff_Frame.hireDate_TextField.setText(hireDate);
        //        editStaff_Frame.status_ComboBox.setSelectedIndex(status);
    }//GEN-LAST:event_editPenaltyTicket_ButtonActionPerformed

    private void refreshPenaltyTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPenaltyTicket_ButtonActionPerformed

    }//GEN-LAST:event_refreshPenaltyTicket_ButtonActionPerformed

    private void addPenalty_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPenalty_ButtonActionPerformed
        new AddPenalty_Frame().setVisible(true); 
    }//GEN-LAST:event_addPenalty_ButtonActionPerformed

    private void editPenalty_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPenalty_ButtonActionPerformed
        //        int index = staff_Table.getSelectedRow();
        //        TableModel model = staff_Table.getModel();
        //
        //        if (index == -1) {
            //            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            //            return;
            //        }
        //
        //        String id = model.getValueAt(index, 0).toString();
        //        String fullName = model.getValueAt(index, 1).toString();
        //        String email = model.getValueAt(index, 2).toString();
        //        String phone = model.getValueAt(index, 3).toString();
        //        String address = model.getValueAt(index, 4).toString();
        //        String hireDate = model.getValueAt(index, 5).toString();
        //        int status = ("Đang làm việc".equals(model.getValueAt(index, 6).toString())) ? 0 : 1;
        //
                EditPenalty_Frame editPenalty_Frame = new EditPenalty_Frame();
                editPenalty_Frame.setVisible(true);
        //
        //        editStaff_Frame.id_TextField.setText(id);
        //        editStaff_Frame.fullname_TextField.setText(fullName);
        //        editStaff_Frame.email_TextField.setText(email);
        //        editStaff_Frame.phone_TextField.setText(phone);
        //        editStaff_Frame.address_TextField.setText(address);
        //        editStaff_Frame.hireDate_TextField.setText(hireDate);
        //        editStaff_Frame.status_ComboBox.setSelectedIndex(status);
    }//GEN-LAST:event_editPenalty_ButtonActionPerformed

    private void refreshPenaltyTable_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPenaltyTable_ButtonActionPerformed
        //        DefaultTableModel tableModel = (DefaultTableModel) staff_Table.getModel();
        //        ActionOnGUI.showDataOnTable(tableModel, staffBUS.getAllStaff());
        //
        //        search_TextField.setText("");
        //        status_ComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_refreshPenaltyTable_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenaltyTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenaltyTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenaltyTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenaltyTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenaltyTicket_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PenaltyTicket_Panel;
    private javax.swing.JPanel Penalty_Panel;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JButton addPenaltyTicket_Button;
    private javax.swing.JButton addPenalty_Button;
    private javax.swing.JButton editPenaltyTicket_Button;
    private javax.swing.JButton editPenalty_Button;
    private com.toedter.calendar.JDateChooser fromDate_DateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable penaltyTicket_Table;
    private javax.swing.JTable penalty_Table;
    private javax.swing.JButton refreshPenaltyTable_Button;
    private javax.swing.JButton refreshPenaltyTicket_Button;
    private javax.swing.JTextField searchPenaltyTicket_TextField;
    private javax.swing.JTextField searchPenalty_TextField;
    private javax.swing.JComboBox<String> sort_ComboBox;
    private com.toedter.calendar.JDateChooser toDate_DateChooser;
    // End of variables declaration//GEN-END:variables
}
